### ISSUE TITLE
Support for data-only dumps (--no-create-info)

### ISSUE THREAD

**Issue by gramstrong** [ppomes/myanon#17]
It would be a really nice feature for myself if it could parse a data-only dump (`mysqldump --no-create-info`). I fiddled with it for a while and couldn't get it to work.

An easy workaround for now is to process the entire dump, and then just remove the create statements from the resulting script. This is a great little tool, thank you!

**Comment by ppomes** [comment]
Hi,

Without any option, mysqldump produces insert/update statements without column names. That's why, the tool needs create statements to know the position of fields in table. This position is used to anonymize the right values in insert/update statements.

I guess you would like to have support for mysqldump --no-create-info --complete-insert ?

Furthermore, the field type is currently used to deduce if the anonymized value should be quoted or not (this could be improved)

Pierre

**Comment by ppomes** [comment]
Best workaround for now: mysqldump db | myanon -f myanon.cfg | egrep '(INSERT|REPLACE)' (not tested). 

@gramstrong , could it be ok for you?
