### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by crummy** [ppomes/myanon#22]
Is there an official myanon docker image on Docker Hub or elsewhere?

**Comment by check24-danielpaschsannapiu** [comment]
I would need one. 

Building of it seems to fail for me. 
(I'm on arm (Apple M1 Max)

```
0.605 make[3]: Leaving directory '/app/main'
0.606 make[3]: *** [Makefile:448: myanon-configscanner.o] Error 1
0.606 make[2]: Leaving directory '/app/main'
0.606 make[2]: *** [Makefile:315: all] Error 2
0.606 make[1]: *** [Makefile:428: all-recursive] Error 1
0.606 make[1]: Leaving directory '/app'
0.606 make: *** [Makefile:348: all] Error 2
------
Dockerfile:7
--------------------
   5 |     RUN ./autogen.sh
   6 |     RUN ./configure
   7 | >>> RUN make LDFLAGS="-static"
   8 |
   9 |     FROM alpine:3.16.2
--------------------
ERROR: failed to solve: process "/bin/sh -c make LDFLAGS=\"-static\"" did not complete successfully: exit code: 2
```

**Comment by ppomes** [comment]
Hi! I published images, ppomes/myanon on Docker Hub

**Comment by check24-danielpaschsannapiu** [comment]
Just wanted to note that you can do it automatically with github actions and publish directly to github. 

I think that makes your workflow easier because you don't need to do anything besides push to master. 

My example project:
https://github.com/gempir/justlog/blob/main/.github/workflows/docker-publish.yml#L40
